- .github/workflows/notify.yml
Create a new github action to notify us on slack every 2 hours about prs that need review, have requested changes, and are approved.
> Add slack notification action

- .github/workflows/notify.yml
Don't notify if nothing to notify about.
> Don't notify when nothing to notify.

- .github/workflows/notify.yml
Change the space into a %20 for the url link
> Fix url link

- .github/workflows/ci.yml
Logfile package will now be called logs-[repo name]-[pr#]-[last commit sha]
> [VDO-5591] Make unique name for uploaded logs

- src/c++/devices/common.h
- src/c++/devices/corruptor/dmCorruptor.c
- src/c++/devices/dory/dmDory.c
- src/c++/devices/flushnop/dmFlush.c
- src/c++/devices/fua/dmFua.c
- src/c++/devices/tracer/dmTracer.c
- src/c++/uds/src/uds/errors.c
- src/c++/uds/src/uds/memory-alloc.h
- src/c++/uds/src/uds/permassert.h
- src/c++/uds/src/uds/volume.c
- src/c++/uds/userLinux/uds/linux/build_bug.h
- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/encodings.c
- src/c++/vdo/base/histogram.c
- src/c++/vdo/base/int-map.c
- src/c++/vdo/base/packer.c
- src/c++/vdo/base/pointer-map.c
- src/c++/vdo/base/recovery-journal.c
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/base/status-codes.c
- src/c++/vdo/base/vio.c
- src/packaging/src-dist/MANIFEST.yaml
Also convert STATIC_ASSERT_SIZEOF callers to using BUILD_BUG_ON.
> dm vdo: use BUILD_BUG_ON instead of STATIC_ASSERT

- .github/workflows/notify.yml
update the cron job to offset for UTC
> make hours close to est

- .github/workflows/ci.yml
Add if statements to all jobs to block them from running if PR is a draft
> Update ci.yml so draft PRs don't run CI.

- src/perl/Permabit/KernelUtils.pm
When setting the kernel memory limit, put a bound on the number of
iterations and then give up and clean up.
Tested with LowMemGenData01 on a pfarm.
> don't loop forever trying to set the kernel mem= option

- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/block-map.h
- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/data-vio.h
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/dump.c
- src/c++/vdo/base/flush.c
- src/c++/vdo/base/flush.h
- src/c++/vdo/base/physical-zone.c
- src/c++/vdo/base/recovery-journal.c
- src/c++/vdo/base/recovery-journal.h
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/base/slab-depot.h
- src/c++/vdo/base/vio.c
- src/c++/vdo/base/vio.h
- src/c++/vdo/base/wait-queue.c
- src/c++/vdo/base/wait-queue.h
- src/c++/vdo/tests/BlockMapTreeWrites_t1.c
- src/c++/vdo/tests/RecoveryJournal_t1.c
- src/c++/vdo/tests/RecoveryMode_t1.c
- src/c++/vdo/tests/RefCounts_t1.c
- src/c++/vdo/tests/SlabJournalRecovery_t1.c
- src/c++/vdo/tests/SlabJournal_t2.c
- src/c++/vdo/tests/SlabRebuild_t1.c
- src/c++/vdo/tests/SlabSummary_t2.c
- src/c++/vdo/tests/VIOPool_t1.c
- src/c++/vdo/tests/WaitQueue_t1.c
- src/c++/vdo/tests/blockAllocatorUtils.c
- src/c++/vdo/tests/slabSummaryUtils.c
- src/c++/vdo/tests/slabSummaryUtils.h
This is an adaption of Mike's suggested changes to wait-queue, mostly changes to structure and function names to use more specific prefixes.
> [VDO-5601] Adapt wait-queue interface renaming

- src/c++/vdo/base/dedupe.c
When Mike Snitzer applied the commits in vdo-devel/41 upstream, he made some minor adjustments. This patch applies those adjustments back to vdo-devel so our trees will continue to match.
Compare commit e244dbdff1764c7cc1c73afc6a219f8146c6fb0 from vdo-devel/41 to upstream commit 	5d5aebb46358e3a87046a4d75e271fbb895ae1fb on dm-vdo.
> [VDO-5597] dm vdo dedupe: realign with upstream branch

- .github/workflows/ci.yml
Have done some additional cleanup to the ci action. 
1. display info at start of every ci run. also fixed log file name at this point.
2. assign reviewers even for draft prs
3. remove trailing spaces
4. fix indenting
5. remove unused REPO variable
> Add additional cleanup and small improvements

- src/tools/vdorecover/vdorecover
> [VDO-5637] Updated vdorecover to work on LVMVDO volumes

- src/perl/Permabit/FileSystem.pm
Fedora 39 has fsck support for checking the "orphan file" status in ext4, and will report if the orphan_present flag is set but the orphan file is empty. It's a reasonable and normal state if file system updates are interrupted in between metadata blocks, as they are for rebuild tests, since multiple blocks can't get updated atomically.
> Allow fsck exit status 1 (filesystem errors corrected). [VDO-5638]

- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/block-map.h
Ingest some commit making minor adjustments in block-map.c from dm-vdo-wip.
Also fixed a typo in Mike's commit message.
> [VDO-5654] Ingest minor block map fixes

- src/c++/uds/src/uds/index-layout.c
- src/c++/uds/src/uds/index-page-map.c
- src/c++/uds/src/uds/index-session.c
- src/c++/uds/src/uds/index.c
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/slab-depot.c
Merge three of Mike Snitzer's patches:
dm vdo index: fix various small nits
dm vdo dedupe: fix various small nits
dm vdo slab-depot: fix various small nits
> Fix small nits

- src/c++/uds/src/uds/chapter-index.c
- src/c++/uds/src/uds/delta-index.c
- src/c++/uds/src/uds/delta-index.h
- src/c++/uds/src/uds/string-utils.c
- src/c++/vdo/base/block-map.h
- src/c++/vdo/base/constants.h
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/encodings.h
- src/c++/vdo/base/flush.c
- src/c++/vdo/base/recovery-journal.h
- src/c++/vdo/base/statistics.h
- src/c++/vdo/base/vdo.h
- src/c++/vdo/base/vio.c
Ingest Mike's upstream patches regarding small nits and formatting fixes. 
The first commit was modified to make necessary includes being removed in the upstream patch available in userspace and internal testing.
> [VDO-5678] Ingest formatting patches from upstream

- src/c++/uds/src/uds/volume-index.c
Ingest the upstream patch from Harshit Mogalapalli to fix an assertion in volume-index.c.
> [VDO-5689] Ingest upstream assertion fix

- .github/workflows/notify.yml
Remove draft PRs from slack notifications
> filter out draft PRs from notifications

- src/c++/devices/dory/dmDory.c
- src/c++/uds/src/uds/delta-index.c
- src/c++/uds/src/uds/delta-index.h
- src/c++/uds/src/uds/event-count.c
- src/c++/vdo/base/admin-state.c
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/base/encodings.c
- src/c++/vdo/base/flush.c
- src/c++/vdo/base/logical-zone.c
- src/c++/vdo/base/physical-zone.c
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/base/vdo.c
- src/c++/vdo/tests/vdoTestBase.c
This includes upstream commits from Jiapeng Chong, as well as various issues I've noticed for myself.
> [VDO-5704] Fix various comment errors

- doc/vdo.rst
Add documentation about metadata size and using the vdo estimator to estimate savings.
> [VDO-5701] Document metadata usage

- src/perl/Permabit/ModuleBase.pm
The previous implementation for logging an error in postinstall commands would treat the "rpm -i" as failing, and not remove the binary package, although RPM considered the installation successful enough to leave the package there. This caused checkServer.pl failures.
Replace the "checker" approach with an additional step run after "rpm -i", checking the DKMS output in the new step. If an error is detected, the previous "successful" steps are cleaned up, including first removing the package just installed.
The assertion call logs the matching string, which includes the full text of the build log, when failing.
> Clean up properly after module build failure. [VDO-5603]

- src/perl/Permabit/VolumeGroup.pm
Add the use of our specialized config to the lvremove commands for thin devices.
> [VDO-5724] Fix BlockDevice01::testThin

- src/packaging/github/changelog
Add a changelog file for release versions.
> Release version 8.3.0.70

- src/perl/Permabit/SupportedScenarios.yaml
- src/perl/Permabit/SupportedVersions.pm
- src/perl/nightly/NightlyBuildType/VDOCheckin.pm
- src/perl/nightly/NightlyRunRules.pm
- src/perl/udstest/Makefile
- src/perl/vdotest/Makefile
- src/perl/vdotest/vdotests.suites
Diable FEDORA38 from testing and replace any build reference from FEDORA38 to FEDORA39.
> dm vdo: Disable FEDORA38 testing and replace head with FEDORA39.

- src/tools/installers/CURRENT_VERSION
This branch tracks releases for latest versions of Fedora, and for RHEL 10.
> [PR-5773] Fix release numbers on release branch

- src/perl/Permabit/SupportedVersions.pm
- src/perl/nightly/NightlyRunRules.pm
- src/perl/udstest/udstests.suites
- src/perl/vdotest/VDOTest.pm
- src/perl/vdotest/vdotests.suites
Update test suites to start running tests on FEDORA40 systems.
> Add FEDORA40 tests

- src/c++/vdo/base/repair.c
- src/c++/vdo/base/slab-depot.c
Merge three changes from author Kuan-Wei Chiu <visitorckw@gmail.com>:
lib min_heap: Rename min_heapify() to min_heap_sift_down()
Link: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/md/dm-vdo?id=1a4ff1407a75d831131dfa3e8d2cad1910c26158
lib min_heap: Add args for min_heap_callbacks
Link: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/md/dm-vdo?id=156c8066a998aba49dc7d0d5469caa28578586f5
lib min_heap: Add type safe interface
Link: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/md/dm-vdo?id=a8d3930625b12baf8f5da5f6610493b0e4b2e898
These changes are needed to build vdo with the latest mainline-next.
We do not know when these changes will roll into RAWHIDE and RHEL. We will use …
> [VDO 5784] dm vdo lib min_heap: Update min_heap for mainline-next build

- src/c++/vdo/base/dm-vdo-target.c
Commit 4f563a64732d ("block: add a max_user_discard_sectors queue limit") changed block core to set max_discard_sectors to:
min(lim->max_hw_discard_sectors, lim->max_user_discard_sectors)
Commit 825d8bbd2f32cb229c3b6653bd454832c3c20acb made fixes to dm to deal with this, by replacing the use of max_discard_sectors with max_hw_discard_sectors. Unfortunately, vdo did not get fixed at that time. I don't think vdo was 
in the kernel at the time of the original fix.
This fix replaces the use of max_discard_sectors in vdo's io_hint function with the use of max_hw_discard_sectors. This will be true for all versions that are 6.10.0 and above.
> [VDO-5791] Update VDO based on dm discard change

- src/c++/uds/userLinux/uds/minisyslog.c
- src/c++/vdo/user/fileLayer.c
- src/c++/vdo/user/vdoConfig.c
- src/c++/vdo/user/vdoFormat.c
- src/c++/vdo/user/vdoStatsWriter.c
- src/tools/adaptLVM/adaptlvm
- src/tools/vdorecover/vdorecover
This series fixes a number of issues from the OpenSacnHub results for our RHEL 10 user package build.
> Fix some user tools warnings

- src/c++/vdo/base/int-map.c
- src/c++/vdo/base/repair.c
Fix kerneldoc warnings flagged by automated checkers upstream.
> Fix kerneldoc warnings

- doc/vdo.rst
- src/perl/bin/transformUpstreamPatch.pl
Patch from Masatake Yamato upstream, plus infrastructure improvements to handle doc files.
> Ingest change to fix vdo documentation formatting

- src/packaging/github/changelog
vdo 8.3.0.72:
* Improved vdoformat error handling.
* Added clang support.
* General code clean up and simplification.
> Add changelog for 8.3.0.72 release

- src/perl/Permabit/SupportedScenarios.yaml
- src/perl/Permabit/SupportedVersions.pm
- src/perl/dmtest/Makefile
- src/perl/nightly/NightlyBuildType/VDOCheckin.pm
- src/perl/nightly/NightlyRunRules.pm
- src/perl/udstest/Makefile
- src/perl/udstest/udstests.suites
- src/perl/vdotest/Makefile
- src/perl/vdotest/vdotests.suites
[TECH 181] Disable FEDORA39 from testing and replace any build reference from FEDORA39 to FEDORA40.
> dm vdo: Disable FEDORA39 testing and replace head with FEDORA40

- src/perl/Permabit/SupportedVersions.pm
- src/perl/nightly/NightlyRunRules.pm
- src/perl/udstest/udstests.suites
- src/perl/vdotest/VDOTest.pm
- src/perl/vdotest/vdotests.suites
Update various files to start FEDORA41 testing.
> [TECH 181] dm vdo test: enable FEDORA41 tests

- .github/workflows/ci.yml
Replace dm-vdo with specific usernames to get this action to work
> Update ci.yml to use usernames directly.

- src/c++/vdo/tests/BlockMapTreeWrites_t1.c
Loosen the assertion in assertGeneration because it is not true as written. It is possible (though rare) for a flush for generation N to be enqueued while there are still pages from generation N-1 that have not been enqueued yet.
In particular, the problem in test set up can only happen because  the test is writing previously uninitialized block map pages, which are written twice, and the test only cares about the second write. In cases where the first write on the pages from generation 2 are slow, and the first write for the flusher from generation 3 is fast, the second flush write can be renqueued before the second writes from the previous generation have been enqueued. This race cannot happen with previously initialized block map pages
I believe the test set up could be rearranged to …
> [VDO-5708] Fix race in BlockMapTreeWrites_t1

- src/perl/Permabit/SupportedVersions.pm
- src/perl/nightly/NightlyRunRules.pm
- src/perl/udstest/udstests.suites
- src/perl/vdotest/VDOTest.pm
- src/perl/vdotest/vdotests.suites
Update various files to start FEDORA42 testing.
> [TECH-203] dm vdo test: enable FEDORA42 tests
