- src/c++/uds/userLinux/uds/blkdev.c
With Fedora 37 and Fedora 38, 6.5 kernel version and above, blkdev_put definition has changed. We need to use VDO_USE_ALTERNATE to redefine blkdev_put base on the kernel version similar to what we did with blkdev_get_by_path.
This change fixes a bug introduced by perforce change 158874.
> Redefine blkdev_put using VDO_USE_ALTERNATE macro.

- .github/workflows/notify.yml
Only run notifications weekdays during the hours of 8am to 10pm
> Restrict notification runs

- src/perl/bin/transformUpstreamPatch.pl
Create transformUpstreamPatch.pl, which rewrites file paths in a patch file from the upstream VDO location to the correct file location in the vdo-devel tree.
> Add a script to transform patches for vdo-devel

- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/block-map.h
This change avoids a compiler warning about unused variables. It also reflects a change that Mike made when incorporating the v4 baseline, so it keeps vdo-devel in sync with upstream.
> [VDO-5609] dm vdo block-map: localize constants

- src/perl/Permabit/BlockDevice/RAID.pm
Our RAID device exists when the machine comes back up during emergency reboot, so we should not have mdadm --create in the activate method of RAID.pm. We will move that to the setup function, thus only creating once, and will move the stop method to the destroy method. We will remove the activate and stop functionality. This should be fine since RAID is a BOTTOM device and will not have anything underneath it that needs the RAID to be stopped during stop/start lifecycle.
> VDO-5610 fix RAID during emergency reboot

- src/c++/vdo/base/int-map.c
- src/c++/vdo/base/pointer-map.c
Fix a discrepancy between commit 45f29e4a28dc "dm vdo: use BUILD_BUG_ON instead of STATIC_ASSERT" and Mike's original change that was its basis.
When going upstream, this commit will be merged with 45f29e4a28dc "dm vdo: use BUILD_BUG_ON instead of STATIC_ASSERT".
> [VDO-5598] Adjust BUILD_BUG_ON location

- src/packaging/kpatch/MANIFEST.yaml
- src/packaging/kpatch/Makefile
- src/packaging/kpatch/commit_to_overlay.sh
Streamline the overlay process by removing some unnecessary steps and some cruft that should not be added to the kernel tree.
Also add the ability to specify a series of commits by pulling them from a merge commit.
> [TECH-151] Improve the kernel overlay script

- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/io-submitter.c
- src/c++/vdo/base/io-submitter.h
- src/c++/vdo/base/repair.c
- src/c++/vdo/base/slab-depot.c
These commits represent a few more formatting fixes picked out of the hash-mp, io-submitter, and wait-queue series. I thought they should got rolled into the general formatting change, especially in places where the formatting change changed lines differently than Mike did, resulting in multiple changes to the same code statements.
When going upstream, these changes will be squashed into the large reformatting commits.
> [VDO-5602] Fix more formatting issues

- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/io-submitter.c
- src/c++/vdo/base/io-submitter.h
- src/c++/vdo/base/packer.c
- src/c++/vdo/base/recovery-journal.c
- src/c++/vdo/base/repair.c
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/base/vdo.c
Apply Mike's upstream patch series for renaming io-submitter functions and adjusting formatting. Also made a few edits to spacing for consistency in alignment of parameters. 
The new patch in this series renames submit_vio (previously process_vio_io) to vdo_submit_vio for consistency with the other non-static function names.
> [VDO-5600] Apply io-submitter changes from upstream

- src/perl/Permabit/SupportedScenarios.yaml
- src/perl/Permabit/SupportedVersions.yaml
- src/perl/vdotest/VDOTest/SimpleMigration.pm
Some of the tests in SimpleMigration.pm have been failing nightly for several weeks due to being unable to load the kvdo module. The migration tests are a special case of tests that involve building the kvdo module manually within the Upgrade device logic. As such, the root issue is that the named versions in the tests (particularly 8.2.1.3 and 8.2.1-current) are unable to build against newer kernels. 
To correct the issue, the SupportedVersions.yaml and SupportedScenarios.yaml files needed to be modified to include more recent module versions that are able to successfully build against recent kernels, and the associated SimpleMigration tests needed to be modified to use the more recent module versions.
> [VDO-5579] dm vdo: Correct migration test failures

- src/packaging/kpatch/MANIFEST.yaml
Explicitly define VDO_UPSTREAM in the uds kernel directory so that it will get stripped from uds-threads.c.
This removes the last difference between the tree as prepared by the overlay script and the actual upstream repo.
> [TECH-151] Fix unifdef artifact

- src/perl/Permabit/SupportedScenarios.yaml
- src/perl/Permabit/SupportedVersions.pm
- src/perl/nightly/NightlyBuildType/VDOCheckin.pm
- src/perl/nightly/NightlyRunRules.pm
- src/perl/udstest/Makefile
- src/perl/udstest/udstests.suites
- src/perl/vdotest/Makefile
- src/perl/vdotest/vdotests.suites
With the default builder going from Fedora 37 to Fedora 38, it is not clear that tests will still be able to build and run on Fedora 37. However, we also plan to retire Fedora 37 soon, so we can stop running tests on Fedora 37 now.
Move test builds and commands which only ran on Fedora 37 to run on Fedora 38 instead. Remove Fedora37 upgrade scenarios and replace them with Fedora 38 scenarios as appropriate.
> Disable Fedora 37 testing

- src/c++/uds/kernelLinux/tests/Makefile
- src/c++/uds/kernelLinux/tests/albtest.c
- src/c++/uds/kernelLinux/tests/getTestIndexNames.c
This is actually about making the mainline-next kernel builds work. The latest kernel appears to be 6.7rc3, and one of the mitigations should only compile on a 6.7 or later kernel.
> [TECH-156] Adapt to changes in the 6.7 kernel

- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/base/slab-depot.c
dm_kcopyd_client_create() returns an ERR_PTR so its return must be checked with IS_ERR().
This change is based on a suggestion from Mike Snitzer, in https://git.kernel.org/pub/scm/linux/kernel/git/device-mapper/linux-dm.git with commit id: 9b935003bbb46f7cefa8c6e7b17b0cf457a65483
We need to include <linux/err.h> to use IS_ERR and ERR_PTR.
> dm vdo: fix how dm_kcopyd_client_create() failure is checked

- src/c++/devices/flushnop/dmFlush.c
- src/c++/devices/tracer/traceLogger.h
Add some missing static declarations in the flush device. Add a missing prototype to a tracer device header.
With these additional changes, the linux-vdo-against-latest-kernel-snapshot jenkins job should start succeeding again.
> [TECH-156] Update C test devices for 6.7 kernel

- .github/workflows/ci.yml
Add some code to output some useful information for when CI runs on a PR. Currently we're going to show repository owner / name, pr number, pr commit, and log file name (to look for on test failure)
> [VDO-5591] Make log name correct and consistent between public and private testing

- .github/workflows/ci.yml
We want to output useful information about the PR that is firing the CI job. The info includes the org and repo the pr is for. We also want to use org/repo as part of a unique name for log files. 
Unfortunately we've been using the wrong field names for those values. After printing out the github event context when the event fired, we were able to determine that the context for what we want is github.event.repository.name and github.event.repository.owner.login for repo name and repo organization, respectively.
> [VDO-5591] Try again to fix log file based on context dump

- .github/workflows/ci.yml
Remove the context dump code since we no longer need it.
Also Fix a small typo for the repo name in the ci display output section.
> [VDO-5591] Remove debug output since things are now fixed for the log name.

- src/tools/vdorecover/vdorecover
RHEL Jira: VDO-20273
Previous PR https://github.com/dm-vdo/vdo-devel/pull/57 was able to recover space on a MOUNTED lvmvdo volume, but that's not very useful when you can't actually mount the volume due to being out of space (which is the primary use case for this script).  This update fixes that shortcoming and allows the user to recover a 100% physical used LVMVDO volume where the filesystem will not mount.
An example of the messages in `dmesg` for a failing-to-mount XFS filesystem:
```
[ 1898.284578] updateVIOErrorStats: 5828 callbacks suppressed
[ 1898.284600] XFS (dm-2): log I/O error -28
[ 1898.284654] XFS (dm-2): Log I/O error (0x2) detected at xlog_ioend_work+0x74/0x80 [xfs] (fs/xfs/xfs_log.c:1284). Shutting down filesystem
[ 1898.284732] XFS (dm-2): Please unmount the filesystem …
```
> [VDO-5637] Fix vdorecover for umounted LVMVDO volumes

- src/perl/Permabit/FileSystem.pm
- src/perl/vdotest/VDOTest/Vdorecover.pm
The changes in PR [#58](https://github.com/dm-vdo/vdo-devel/pull/58) enabled the Vdorecover perl test to run in nightly testing and corrected an issue with vdostats not being able to be run by the vdorecover utility. As a result, nightly testing was able to uncover a timing issue within testFullFilesystem where the test is intermittently unable to remount the filesystem after recovery due to errors in the order of operations.
> [VDO-5377] Fix vdorecover test timing issues in testFullFilesystem

- src/c++/uds/src/uds/errors.c
- src/c++/uds/src/uds/errors.h
- src/c++/uds/src/uds/index-layout.c
- src/c++/uds/src/uds/index-session.c
- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/base/status-codes.c
- src/c++/vdo/base/status-codes.h
- src/c++/vdo/tests/Load_t1.c
- src/c++/vdo/tests/Resize_t1.c
Ingest Mike's upstream patch series to cleanup UDS error codes and rename the uds and vdo map_to_system_error functions.
The additional commit in this series extends the function renaming to our internal test code.
> [VDO-5657] Ingest error code patches from upstream

- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/data-vio.h
- src/c++/vdo/base/types.h
Eliminate use of "trim" in favor of "discard" since it reflects the top-level Linux discard primative rather than the ATA specific ditto.
> [VDO-5655] dm vdo data-vio: rename is_trim flag to is_discard

- src/c++/uds/src/tests/Volume_n4.c
This test is failing intermittently since we moved to the pmifarms. Disable it so that it doesn't interfere with upstream development.
> [VDO-5642] Disable Volume_n4 StumblingGet test

- src/perl/vdotest/VDOTest/Sysfs.pm
Remove nr_requests from Sysfs.pm test, as the kernel source has been changed so that the req based drivers are the only ones that have that field now.
> [VDO-5592] Remove nr_requests check

- src/packaging/kpatch/Makefile
Copy our Makefile and Kconfig files into the dm-vdo directory in the prepare step instead of in checkpatch. This fixes an error from PR vdo-devel/71, which put this operation in the wrong target.
> Copy Makefile and Kconfig during prepare step

- src/Makefile
- src/packaging/dmlinux/Makefile
- src/packaging/dmlinux/kernel/Makefile
- src/packaging/dmlinux/kvdo.spec
- src/perl/vdotest/Makefile
- src/perl/vdotest/VDOTest.pm
In order to test dm-vdo/dm-linux using our current perl infrastructure, we're going to create a kvdo srpm using source files from the dm-vdo/dm-linux repo. Then we will run vdotests using that srpm instead of the normal one built using dm-vdo/vdo-devel sources. This PR contains the support to build the srpm and run the tests using it. The main target to do all this is in src/Makefile and will be called by the CI for dm-linux. That work is not part of this PR and instead will be in a PR for the dm-vdo/dm-linux repo once this code is checked in. The changes for this PR consist of the following:
src/Makefile - the target to be called from the CI to create the SRPM and run the tests.
src/packaging/dmlinux/* - the code to create the SRPM using the dm-linux sources. Requires setting of …
> Add support to test dm-linux using vdo-devel perl infra

- doc/vdo-design.rst
Incorporate the contents of the VIO lifecycle doc into existing kernel documentation:
https://docs.google.com/document/d/1qqhjK5vs_CG7V3OatKxIyNjttHH4wX4vQVgT-Nvtdfc/
That document was originally an embellishment of the "Write Path" section of vdo-design.rst, plus some additional details, so I chose to incorporate the new information into the existing doc rather than add a new file as previously discussed.
> [VDO-5665] Add vio lifecycle details to documentation

- doc/vdo-design.rst
- src/c++/vdo/base/block-map.h
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/recovery-journal.h
- src/c++/vdo/base/slab-depot.h
The first commit contains suggestions that Ken had for the previous PR, vdo-devel/79. When going upstream I intend to squash this commit into that one.
The second commit adds a section to the doc of each major zoned components to bring attention to our singled-threaded zone model so readers understand why we don't do have to do fine-grained locking. I also added some basic block map documentation because we didn't seem to have any already.
> [VDO-5665] Improve doc comments about zoning and asynchronous I/O

- doc/vdo-design.rst
Remove extra whitespace in design doc. Mike removed this whitespace when accepting the doc commit upstream, but we need to remove it internally to stay in sync.
> [VDO-5665] Realign design doc with upstream

- src/c++/uds/src/uds/chapter-index.h
- src/c++/uds/src/uds/volume-index.h
- src/c++/vdo/base/encodings.c
- src/c++/vdo/base/encodings.h
The first commit is an adjustment to Susan's earlier change 9462281cde95 in PR vdo-devel/77. The  adjustment makes sense upstream but it makes it difficult to deal with userspace usage of the relevant constants. This commit will be combined with Susan's earlier one when going upstream so that the result looks like Mike's commit on dm-vdo-wip.
The second commit is a straightforward ingestion of an upstream suggestion.
> [VDO-5675] Ingest simplifications to constant definitions

- src/perl/bin/transformUpstreamPatch.pl
This is a tool change to allow the ingestion script to deal with files found in the indexer subdirectory (that is, UDS files). The upstream work-in-progress branch has already created that subdirectory so this is necessary to ingest any commits made after that point.
> [VDO-5667] Adjust ingestion script for subdirectory structure

- src/c++/uds/kernelLinux/uds/uds-threads.c
- src/c++/vdo/base/dm-vdo-target.c
Ingest upstream patch 'dm vdo: tweak wait_for_completion_interruptible callers'.
> [VDO-5682] Ingest patch to add wait in rescheduling loops from upstream

- src/c++/uds/kernelLinux/uds/logger.c
- src/c++/uds/src/uds/index-session.c
- src/c++/uds/src/uds/logger.h
- src/c++/uds/userLinux/tests/Logger_t1.c
[VDO-5677] Ingest commits: logging changes
Stops short of actually using DM's various logging macros (e.g. DMERR, DMINFO, etc) because VDO's logger isn't quite compatible with them.
Also switch emit_log_message_to_kernel() from open-coding printk with log-level to using corresponding pr_ macro.
> [VDO-5677] dm vdo logger: update logging to start with "device-mapper: vdo"

- src/c++/vdo/base/block-map.c
Ingest upstream patch to rename page state name from "UDS_FREE" to "FREE".
> [VDO-5694] Ingest block-map patch from upstream

- src/c++/uds/kernelLinux/uds/memory-alloc.c
- src/c++/uds/src/uds/sparse-cache.c
- src/c++/uds/src/uds/uds-threads.h
- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/base/funnel-workqueue.c
- src/c++/vdo/base/packer.c
- src/c++/vdo/base/packer.h
- src/c++/vdo/base/repair.c
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/base/vdo.c
- src/c++/vdo/base/vio.c
Remove internal ticket references from the codebase in vdo and uds, adjusting the comments for clarity or to provide additional information from the previously-referenced tickets as necessary.
More extensive modification of the comment in vdo/base/packer.c was performed due to referenced function may_vio_block_in_packer() no longer existing.
> [VDO-5671] Remove internal ticket references from vdo and uds

- src/c++/uds/src/uds/index-session.c
Remove an end-of-file newline that crept into vdo-devel/92.
This aligns vdo-devel with the change as squashed into dm-linux/41.
> [VDO-5684] [VDO-5685][VDO-5686] Fix whitespace issue

- src/c++/uds/kernelLinux/uds/logger.c
- src/c++/uds/kernelLinux/uds/thread-registry.c
- src/c++/uds/kernelLinux/uds/thread-utils.c
Add includes statements for current.h into various files to get longarch to build.
Reported when building on loongarch.
Reported-by: Randy Dunlap <rdunlap@infradead.org>
> [VDO-5693] dm vdo: include <asm/current.h> to resolve current being undeclared

- src/c++/vdo/base/message-stats.c
[VDO-5690] Ignore scnprintf return status since it is not necessary.
Change write_* functions type from int to void since we no longer
return any result. Also, clean up any codes that check or use any
scnprintf return results.
check uds_allocate return code which was previous ignored, return
and log error when uds_allocate failed.
Note:
message-stats.c used to be generated and we added the file to our 
tree, VDOSTORY-283.
And snprintf was replaced by scnprinf because snprintf could return
-1 and it can cause problem, [vdo-4907]. 
Reported-by: Dan Carpenter <dan.carpenter@linaro.org>
Signed-off-by: Chung Chung <cchung@redhat.com>
> [VDO-5690] Clean up scnprintf usage

- src/c++/uds/kernelLinux/uds/uds-sysfs.c
- src/c++/uds/src/uds/chapter-index.c
- src/c++/uds/src/uds/delta-index.c
- src/c++/uds/src/uds/delta-index.h
- src/c++/uds/src/uds/geometry.c
- src/c++/uds/src/uds/hash-utils.h
- src/c++/uds/src/uds/index-layout.c
- src/c++/uds/src/uds/index-page-map.c
- src/c++/uds/src/uds/index-session.c
- src/c++/uds/src/uds/index-session.h
- src/c++/uds/src/uds/index.c
- src/c++/uds/src/uds/open-chapter.c
- src/c++/uds/src/uds/sparse-cache.c
- src/c++/uds/src/uds/volume-index.c
- src/c++/uds/src/uds/volume-index.h
- src/c++/uds/src/uds/volume.c
- src/c++/uds/src/uds/volume.h
- src/c++/vdo/base/data-vio.h
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/encodings.h
- src/c++/vdo/base/vdo.h
- src/c++/vdo/user/parseUtils.h
- src/c++/vdo/user/vdoConfig.h
- src/packaging/dmlinux/Makefile
- src/packaging/dmlinux/kernel/Makefile
- src/packaging/github/MANIFEST.yaml
- src/packaging/kpatch/MANIFEST.yaml
- src/packaging/kpatch/Makefile.upstream
- src/packaging/src-dist/kernel/Makefile
Move the core UDS files into a sub-directory upstream. Since the files do not move locally, that means adjusting the spelling of several includes lines, and rewriting some Makefiles to adapt to the new file structure.
The biggest change in the infrastructure is that the packaging/github directory now defines the VDO_UPSTREAM flag and uses the upstream file structure. This allows us to test the upstream build arrangement a little more directly, without having to push changes to the dm-linux repository. It also means that if we do continue to push changes to our own open-source repositories (such as dm-vdo/kvdo), we will reflect the new directory structure there as well as in the kernel.
> [VDO-5667] Move UDS files to indexer sub-directory

- src/c++/vdo/base/dm-vdo-target.c
Fix nonstandard comment formatting for comment moved in vdo-devel/103.
This change is already reflected in the upstream commit.
> [VDO-5680]  Fix comment formatting in dm-vdo-target.c

- src/c++/uds/src/uds/memory-alloc.h
Fix formatting issues in the last commit of vdo-devel/104. I spent so long looking at the larger commit I didn't pay enough attention to the smaller one.
When going upstream, this commit will be squashed into the last commit of vdo-devel/104.
> [VDO-5696] Fix vdo_allocate_extended formatting

- doc/vdo.rst
- src/c++/uds/kernelLinux/uds/logger.c
- src/c++/uds/kernelLinux/uds/uds-module.c
- src/c++/uds/kernelLinux/uds/uds-sysfs.c
- src/c++/uds/src/uds/logger.h
- src/c++/uds/userLinux/uds/logger.c
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/dedupe.h
- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/base/status-codes.c
- src/c++/vdo/base/status-codes.h
- src/c++/vdo/base/sysfs.c
- src/c++/vdo/base/vdo.c
- src/c++/vdo/base/vdo.h
- src/packaging/github/MANIFEST.yaml
- src/packaging/kpatch/MANIFEST.yaml
- src/packaging/kpatch/Makefile.upstream
- src/packaging/rpm/kvdo.spec
- src/perl/Permabit/ModuleBase.pm
- src/perl/bin/transformUpstreamPatch.pl
- src/perl/vdotest/VDOTest/Sysfs.pm
Pull in three changes from Mike Snitzer, and adjust internal code accordingly.
Mike's changes remove our sysfs support, then re-add log_level as a simple numeric module parameter.
Changes from Mike's version:
- conditionalize most code changes on VDO_UPSTREAM
- remove files from manifest instead of deleting them
- change name of now-non-static "log_level" variable in case we're linked into the kernel
- add documentation of the one remaining sysfs field
Also updated the target version number to note the removal of an interface.
> [VDO-5662, VDO-5663] Trim sysfs usage

- src/c++/uds/src/uds/index-layout.c
From mail to dm-devel, 02/26 09:41
Fixes: b46d79bdb82a ("dm vdo: add deduplication index storage interface")
Reported-by: Harshit Mogalapalli <harshit.m.mogalapalli@oracle.com>
> [VDO-5706] Fix use after free in index-layout

- src/c++/uds/kernelLinux/uds/thread-utils.c
- src/c++/uds/kernelLinux/uds/uds-module.c
- src/c++/uds/src/uds/thread-utils.h
- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/base/status-codes.c
[VDO-5700] The first commit removes vdo_perform_once() from the kernel build. It is not necessary because we can initialize what we need at module load time. I left vdo_perform_once() in for userspace because the test runners and userspace utilities don't have a clear initialization bottleneck and I didn't want to worry about accidentally breaking something subtle.
[VDO-5619] The second commit removes the CURRENT_VERSION constant from upstream. Upstream the only version we care about is the kernel version, so a separate field in meaningless at best and confusing at worst. However, we do still want an identifiable version for internal tests and for RHEL8/9 releases, so this is only removed for VDO_UPSTREAM.
[VDO-5709] This is a tiny format fix that came in to the mailing list this morning. …
> [VDO-5700][VDO-5619][VDO-5709] Adopt various minor fixes

- src/c++/uds/src/uds/murmurhash3.c
The murmurhash3.c code was imported from a user-mode library that explicitly tested byte order macros and called __builtin functions that aren’t well supported in the kernel on all architectures.
Reported-by: Guenter Roeck <linux@roeck-us.net>
> dm vdo: use kernel byteswapping routines instead of GCC ones [VDO-5720]

- src/perl/Permabit/VolumeGroup.pm
Move the use of use_devicesfile=0 to always be used. It seems like when we are now under a raid, we can't properly reactivate lvm volumes after a reboot. Eventually, we should start using the devices file itself by adding and removing our devices during a test, but it requires a bit of refactoring with ISCSI.pm and I think we can delay that work for now.
> [VDO-5643] Fix reboot issues with lvm by always uses use_devicesfile=0

- src/c++/uds/src/uds/murmurhash3.c
Per suggestion from Eric Biggers on dm-devel, don't use cpu_to_le64 and friends, use get_unaligned_le64 and friends. Call them directly rather than via a wrapper function, since we don't need the conditional mess. Use the same code for user mode, as well.
> Murmurhash byteswapping fix v2 [VDO-5720]

- src/perl/Permabit/BlockDevice/VDO.pm
- src/perl/Permabit/BlockDevice/VDO/Upgrade.pm
- src/perl/Permabit/UserMachine.pm
- src/perl/vdotest/VDOTest.pm
The purpose behind this code movement is to improve clarity around how userBinaryDir is set and used by making it consistent with what we already do for property scratchDir. Furthermore, having the user tool binaries installed within runDir provides an added benefit of automatic cleanup at test failure or completion through existing mechanisms.
The removal of the userBinaryDir property and function findNamedExecutable() from RemoteMachine.pm will be done in a subsequent change in order to prevent breaking nightly testing.
> [VDO-5560] Modify the user tool binary install location to within runDir

- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/fake/linux/bio.h
- src/c++/vdo/fake/linux/bvec.h
- src/c++/vdo/fake/linux/highmem.h
- src/c++/vdo/fake/linux/kernel.h
- src/c++/vdo/fake/linux/min_heap.h
- src/packaging/rpm/MANIFEST.yaml
- src/packaging/rpm/kernel/Makefile
[VDO-5715] RAWHIDE updated some of the system's .h files. We need to update our .h files to reflect thoes changes. Also, removed some of the obsolete definitions that are no longer needed but causes problems.
Also, we discover that missing-declarations and missing-prototypes were not turned on by default in gcc before 14.0.1.  Some of our codes need to be updated since it is now turned on.
> dm-vdo: Changes are needed to build and test RAWHIDE

- src/c++/uds/src/uds/murmurhash3.c
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202404050327.4ebVLBD3-lkp@intel.com/
> dm-vdo murmurhash: remove unneeded semicolon

- src/c++/uds/kernelLinux/tests/getTestIndexNames.c
Recent changes to the block interface mean that our test code can't access the struct block_device directly. Instead, tests obtain another intermediate structure (struct bdev_handle or struct file) first. These intermediate structures must have the same lifetime as the struct block_device itself. This is handled by creating a new block_device_context structure to hold any additional information we need to track. 
The existing implementation of the 6.7.0 - 6.9.0 case did not remember the struct bdev_handle obtained when opening the device, which resulted in leaking that structure, and more importantly causing bdev_release() to call kfree() on an address in the stack. (It is surprising to me that this does not fail more often than it does.)
Although this code has been used by our tests for …
> [VDO-5743] dm vdo test: manage extra block-related handles correctly

- src/perl/vdotest/VDOTest/RegenerateGeometry.pm
Disable writable storage before failing
Leaving the VDO pool writable seems to be invisible to LVM and so it won't clean up the pool while we try to tear down the storage stack.
> [VDO-5639] Disable writable storage before failing

- src/c++/uds/kernelLinux/tests/RequestQueue_n1.c
The two-argument DEFINE_SEMAPHORE is available now in Fedora and RHEL9. Remove the workaround code and call updated DEFINE_SEMAPHORE.
> dm-vdo: use updated DEFINE_SEMAPHORE macro

- src/Makefile
- src/perl/Permabit/CommandString/DMTest.pm
- src/perl/dmtest/.dmtests.options
- src/perl/dmtest/DMTest.pm
- src/perl/dmtest/DMTest/Grouped.pm
- src/perl/dmtest/DMTest/Separated.pm
- src/perl/dmtest/Makefile
- src/perl/dmtest/dmtests.pl
- src/perl/dmtest/dmtests.suites
- src/perl/dmtest/log.conf
This is the initial perl framework for running dmtest-python tests.
> [VDO-5738] Add perl support for running dmtest tests

- src/perl/dmtest/DMTest/Separated.pm
- src/perl/nightly/NightlyBuildType/VDO.pm
- src/perl/nightly/NightlyBuildType/VDOCheckin.pm
- src/perl/nightly/NightlyRunRules.pm
This adds a single suite to VDO nightly to run the DMTest nightly suite. This is currently contains a single test named "Full". As dmtests are added, the nightly suite definition can be adjusted as appropriate.
> [VDO-5739] Add dmtests to nightly

- src/Makefile
- src/perl/dmtest/DMTest.pm
- src/perl/dmtest/Makefile
We were assuming (incorrectly) that we would only ever be running dmtest suite using dm-linux source code, which uses a different set of SRPMS. I've added in the code to deal with running dmtest using the same SRPM choices that VDOTest.pm does. I've also updated the make files to allow for dm-linux to still be used.
> [VDO-5762] Fix nightly run of DMTest.

- src/perl/Permabit/BlockDevice.pm
- src/perl/Permabit/BlockDevice/ISCSI.pm
- src/perl/Permabit/BlockDevice/VDO.pm
- src/perl/Permabit/BlockDevice/VDO/Managed.pm
- src/perl/Permabit/BlockDevice/VDO/Unmanaged.pm
- src/perl/Permabit/VolumeGroup.pm
Changing our code to use the use_devicesfile=0 config option for lvm commands seems to have broken some other tests that weren't using config options at all. Rather than adding the use_devicesfile=0 option everywhere, it makes more sense to    actually use the devices file itself; since this is what LVM expects us to do. This change makes it so each device in our stack gets added to the system.devices file in /etc/lvm/devices right after they are created on the stack and get removed just     before the device is removed from the stack. In this way, all the devices we care about should be in the devices file.
BlockDevice.pm: Add the device during activation and remove it during deactivation. This is the same spot where the only place in our code we used to use the devices file (in …
> [VDO-5724] Use lvm devices file directly

- src/perl/Permabit/FileSystem.pm
The NFS server appears to hold on to references to some files for a bit otherwise.
Also, assume "systemctl" support and drop "service" path.
> [VDO-5576] Shut down NFS server after stopping export.

- src/c++/devices/common.c
- src/c++/uds/src/uds/io-factory.c
- src/c++/uds/userLinux/tests/getTestIndexNames.c
- src/c++/uds/userLinux/uds/linux/blkdev.h
- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/tests/testDM.c
- src/c++/vdo/tests/vdoTestBase.c
- src/packaging/kpatch/Makefile.upstream
Ingest two upstream commits that went into 6.9.0 outside of the dm-devel tree, to keep us in sync. Also add userspace support for the bdev_nr_bytes change.
This should also incidentally fix the current linux-next build failure.
> Ingest 6.9 kernel changes

- src/Makefile
Inclusion of copying and building kvdo from tarball was intentionally excluded due to no make targets being defined in the tarball Makefile.
> [VDO-5759] Add testing the ability to build from tarballs to the archive target

- src/c++/vdo/user/vdoFillIndex.c
The first commit adds some error-handling to vdoFillIndex so that if it encouters an error, it doesn't leak an open file descriptor for the VDO pool device. This file descriptor can prevent any other process from accessing the file, potentially making it impossible to restart VDO until it cleaned up.
The second commit fixes the actual test failures, by setting a size in the fake block_device that vdoFillIndex constructs. This should have been fixed as part of PR vdo-devel/148, but I didn't notice this use of struct block_device.
> [VDO-5770] Fix tests that use vdoFillIndex

- src/perl/Permabit/BlockDevice/VDO.pm
- src/perl/Permabit/BlockDevice/VDO/LVMManaged.pm
Add flags to record when a VDO device enters a non-standard device state (usually to run user programs), and add cleanup code to stop() to revert those changes before doing the rest of the device cleanup.
> [VDO-5771] Fix non-standard device stacks during vdo stop

- src/perl/vdotest/VDOTest/FullBase.pm
- src/perl/vdotest/VDOTest/FullWarnDmEventd.pm
Update FullWarnDmEventd test expectations. The test is checking for a log message created by our custom dmeventd_lvm trigger, which no longer exists. Now that we no longer register a custom trigger, the default LVM VDO plugin will trigger instead, but its warning message is spelled slightly differently.
Additionally, wrap the dumpMetadata call in FullBase in an eval clause. When the test fails this way, the dumpMetadata operation fails, which has the side-effect of short-circuiting cleanup and log collection.
> [VDO-5776] Fix FullWarnDmEventd

- src/c++/uds/src/uds/index.c
- src/c++/uds/userLinux/uds/asm/unaligned.h
This reflects a change suggested upstream by Jiapeng Chong. It's going to be applied to the dm-devel tree, so apply it to vdo-devel also. If people think it's important I can defer this until we have a proper commit to ingest.
> Use swap macro from kernel in swap_open_chapter()

- src/packaging/github/changelog
* Remove obsolete utilities.
* Fix version numbering.
* Update project decoumentation.
* [Unmentioned] Adopt some streamlining from the kernel side.  This is both minor and irrelevant to the user tools functionality.
File changed:
modified:   README.md
modified:   utils/uds/Makefile
modified:   utils/uds/asm/unaligned.h
modified:   utils/uds/index.c
modified:   utils/uds/io-factory.c
modified:   utils/uds/linux/blkdev.h
modified:   utils/vdo/Makefile
modified:   utils/vdo/man/Makefile
deleted:    utils/vdo/man/vdodmeventd.8
deleted:    utils/vdo/man/vdodumpconfig.8
deleted:    utils/vdo/man/vdoregenerategeometry.8
deleted:    utils/vdo/man/vdosetuuid.8
deleted:    utils/vdo/vdodmeventd.c
deleted:    utils/vdo/vdodumpconfig.c
deleted:    utils/vdo/vdoregenerategeometry.c
deleted: …
> Release version 8.3.0.71

- src/tools/installers/CURRENT_VERSION
On Perforce-based branches, tagAndArchive.pl automatically updates the
version number each time jenkins does a build. However, the script does not work
with github, and it's not clear we want automatic builds of the 8.3 branch anyway.
> Update 8.3 to version 8.3.0.72

- src/perl/Permabit/SupportedScenarios.yaml
- src/perl/Permabit/SupportedVersions.yaml
- src/perl/vdotest/VDOTest/SimpleMigration.pm
Update the scenarios used by the migration tests to include the latest from the Chlorine branch, since the older versions no longer build on our lab machines due to kernel updates in RHEL 9.5.
> [VDO-5789] Update RHEL 9 migration scenarios

- src/perl/nightly/NightlyBuildType/VDO.pm
- src/perl/vdotest/vdotests.suites
Running vdo-devel tests on RHEL9 just isn't that useful any more. There might be merit to running tests against RHEL10 once that becomes available, but we can consider that once it becomes possible.
It would be nice to run some test against a debug kernel, but it's not clear that fedora debug kernels are readily available. The RHEL 9 debug kernel no longer works for us, though.
> [VDO-5778] dm vdo test: stop running tests on RHEL 9

- src/perl/dmtest/DMTest/Separated.pm
- src/perl/dmtest/dmtests.suites
In order to fix this test, we need to create a "dummy" test so we can install dmtest. That way we can run dmtest list to get the set of tests we want to run. Then we can take that list and split it up into a single test per item in the list.
> Fix the Separated.pm test.

- src/perl/Permabit/DistFramework.pm
Use the dm-devel list instead of vdo-devel, as the latter no longer exists. The author field of the framework is only used for changelog entries in the published spec file, but it should still reflect an address that might work.
> Replace use of obsolete vdo-devel mailing list

- src/perl/nightly/NightlyBuildType/VDO.pm
Re-enable the debug test suite, using the new FEDORA40DEBUG machines.
> [VDO-5778] Re-enable debug tests

- src/perl/vdotest/VDOTest/VDOClobber.pm
VDOManagerTestClobber was a test we previously had when vdo manager was our main tool for creating and managing VDO volumes. It consisted of several sub tests that made sure we didn't overwrite existing VDO volumes on a storage device, when calling vdoformat or vdo manager commands like "vdo create".
When we moved to LVM managed VDOs, we removed this test, but we've decided since then that we would like to bring back some of the sub tests.
VDOClobber.pm is the test that attempts that to do that. It uses Unmanaged.pm, which creates VDO volumes directly using dmsetup create and also calls vdoformat directly as well to replicate the previous tests features.
> [VDO-5793] Add tests to make sure we don't accidentally overwrite VDOs.

- doc/vdo.rst
- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/base/message-stats.c
- src/c++/vdo/base/message-stats.h
- src/perl/vdotest/VDOTest/Dmsetup.pm
In previous versions of VDO, we had a user tool called vdoDumpConfig which output configuration info from our geometry block and uds index. We have removed that tool and are replacing the functionality with a new dmsetup message called config, which will output a yaml string containing the same information. The yaml will contain a version number to handle future
modifications to the string.
We have updated the VDO module number so that clients of VDO will know when they can call the new dmsetup message.
> [VDO-5795] Add dmsetup message for returning config info

- src/c++/vdo/base/repair.c
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/fake/linux/min_heap.h
- src/c++/vdo/tests/.gitignore
- src/c++/vdo/tests/BlockMapRecovery_t1.c
- src/c++/vdo/tests/Makefile
In the mainline next build, min_heap set of functions have been completely rewritten and we need to integrate those changes into vdo-devel.  Currently vdo-devel has three build problems:
. vdo-devel fake min_heap.h need to integrate necessary min_heap.h change from mainline next kernel source.
. We need a way to distinguish between RAWHIDE and mainline next repo.
. numberedBlockMapping.h and repairCompletion.h  are being generated.  The files that are currently being generated do not work with mainline next build.
In this PR, we will addressed the above three problems.
> Fix mainline next build problems

- src/c++/vdo/base/dedupe.c
Clear the dedupe context pointer in a data VIO whenever ownership of the context is lost, so that we can't examine it accidentally.
> dm vdo: don't refer to dedupe context after releasing it [RHEL-42515,VDO-5794]

- src/c++/vdo/base/repair.c
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/fake/linux/min_heap.h
The linux-next min_heap code is now integrated into RAWHIDE. Add MACRO to test if a system is RAWHIDE, and use linex-next min_heap code if it is. We also replaced the VDO_USE_ALTERNATE variable with VDO_USE_NEXT if the code block is for the linux-next kernel to clarify the usage.
We also reorder code blocks so that the older code comes first and then the newest code.
> dm vdo: Use VDO_USE_NEXT code with RAWHIDE distro

- src/perl/nightly/NightlyBuildType/VDO.pm
- src/perl/vdotest/VDOTest.pm
- src/perl/vdotest/vdotests.suites
Rename rawhideTests to upstreamTests since we will use the same test suite for both kernels. Also, add upstreamTests in nightly run for both RAWHIDE and FEDORANEXT OS class.
> [TECH-170] Add upstreamTests suite for FEDORANEXT OS class

- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/base/repair.c
- src/c++/vdo/base/status-codes.c
- src/c++/vdo/base/status-codes.h
- src/c++/vdo/tests/OldRecoveryJournal_t1.c
- src/c++/vdo/tests/RecoveryJournal_t2.c
- src/c++/vdo/tests/asyncLayer.c
- src/c++/vdo/tests/journalWritingUtils.c
- src/c++/vdo/tests/journalWritingUtils.h
In the third commit, you will notice that asyncLayer.c was modified to remove a vdo_free() line. This is to correct compilation failures regarding the VDO target being double freed in the case of load failure. Function stopAsyncLayer() already frees the target in the TABLE_LOADED case.
> [VDO-5742] Improve handling of dirty volumes with old recovery journal format

- src/c++/vdo/base/io-submitter.c
VDO creates lists of data bios in places but does not for metadata bios. A sanity check was in place to ensure that no code accidentally did so for metadata, but erroneously assumed the storage layer below wouldn't modify the bi_next field while operating on a bio, so a not-yet-reset bio could have the field set.
Since the check is unnecessary and wrong, remove it.
> dm vdo: remove bad check of bi_next field [VDO-5802]

- src/perl/Permabit/ModuleBase.pm
It missed a failure because stdout said "Failed" and stderr said "failed" but we only checked for "failed" on stdout.
> Update regexp for catching rpm -i errors, and check stderr too.

- src/c++/vdo/base/repair.c
- src/c++/vdo/tests/RecoveryJournal_t2.c
I was not able to reproduce the issue we've been seeing in nightly in the TornWrite tests due to its spurious nature. However, I believe the issue may be due to us checking for invalid blocks after we check for corruption. As such, I have moved around those checks so that we first verify we have a valid recovery journal block before we check if it is corrupted.
These modifications made it possible to simplify the parse_journal_for_recovery() function and eliminate the first loop over the recovery journal blocks that had been added in PR180.
> [VDO-5804] Skip corruption check for invalid recovery journal blocks

- src/c++/vdo/base/repair.c
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/fake/linux/min_heap.h
Kernel release has changed from 6.9 to 6.10.  However min_heap code has not been imported to 6.10 yet. We need to adjust USE_VDO_NEXT comparison from 10 to 11 to adopt this version change.
> dm vdo: adjust USE_VDO_NEXT kernel release number comparison

- src/c++/vdo/base/data-vio.c
- src/c++/vdo/tests/PartialDiscards_t1.c
- src/c++/vdo/tests/ioRequest.c
- src/c++/vdo/tests/ioRequest.h
Due to RHEL-57824, we noticed that unaligned discard bios are not always handled properly, causing VDO to throw assertions and to not properly discard data. Two general types of fixes are required:
First, some splitting logic was incorrect, leading VDO to incorrectly try to acknowledge and clean up the discard vio without doing processing the final segment. This would cause problem for discards that are 4K or less, but which crossed a VDO block boundary.
Second, large discard bios recycle the same data_vio for each subsequent 4K segment, but the data_vio was not being completely reset before processing the segments after the first one. By luck, this only caused problems for a final partial segment, but it was technically incorrect for all segments.
Due to the subtlety of some of these …
> [VDO-5820][RHEL-57824] Fix unaligned discard handling

- src/c++/uds/src/uds/chapter-index.c
To ensure code clarity and prevent potential errors, it's advisable to employ the ';' as a statement separator, except when ',' are intentionally used for specific purposes.
> dm vdo indexer: Convert comma to semicolon

- src/c++/uds/src/uds/murmurhash3.c
This addresses dm-vdo/vdo [issue #69](https://github.com/dm-vdo/vdo/issues/69) by cleaning up the code to remove the alignment requirement, as there is no need for it.
> dm-vdo: remove u64 alignment requirement in murmurhash3 computations

- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/encodings.c
- src/c++/vdo/base/int-map.c
- src/c++/vdo/base/io-submitter.c
- src/c++/vdo/base/packer.c
- src/c++/vdo/base/physical-zone.c
- src/c++/vdo/base/recovery-journal.c
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/base/vdo.c
Apparently some architectures or compilers are stricter about tags like __packed and __always_unused than the ones we use.
Example complaint: https://lore.kernel.org/oe-kbuild-all/202410011107.U2xbVLRA-lkp@intel.com/
The first of these issues can be fixed by moving the __packed label. For__always_unused, I probably could move the tag to make the warning go away, but it's sort of silly to be passing __always_unused parameters to static functions in the same file.
(The second warning should be fixed by a previous comment format change, my first attempt to get rid of these warnings. See PR #173.)
I should note that lkp provides "instructions" for reproducing the build warnings, but they seem to require some packages we don't install by default and I couldn't figure out how to get the build …
> [VDO-5828] Fix kernel format issues

- src/packaging/src-dist/user/utils/uds/Makefile
- src/packaging/src-dist/user/utils/vdo/Makefile
Suggested by dm-vdo/vdo PR #70 (and #71, and #72), add support for clang in the userspace Makefiles. Since our main Makefiles already support clang, this was mostly a matter of copying over the handling.
I elected not to just imported the commits suggested by sgzGary because I think we should use appropriate flags when compiling with clang, and not just remove the warning flags altogether.
> [VDO-5825] Support clang in userspace Makefiles

- src/c++/devices/tracer/dmTracer.c
- src/c++/vdo/base/dm-vdo-target.c
Implement change from author, Christoph Hellwig <hch@lst.de>:
dm: stop using blk_limits_io_{min,opt}
https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/md/dm-vdo?id=0a94a469a4f02bdcc223517fd578810ffc21c548
Remove use of the blk_limits_io_{min,opt} and assign the values directly
to the queue_limits structure.  For the io_opt this is a completely
mechanical change, for io_min it removes flooring the limit to the
physical and logical block size in the particular caller.  But as
blk_validate_limits will do the same later when actually applying the
limits, there still is no change in overall behavior.
Signed-off-by: Christoph Hellwig <hch@lst.de>
Signed-off-by: Mikulas Patocka <mpatocka@redhat.com>
Also remove VDO_USE_ALTERNATE in dm-vdo-target.c to use …
> dm vdo: stop using blk_limits_io_{min,opt}

- src/c++/vdo/user/vdoFormat.c
Error codes used in calls to errx should only use specific values. Previously we used to return our own error codes in a number of places which was incorrect. Replace those values with 1, which is the generic exit error code.
> [VDO-5816] dm vdo user: Fix errx calls to use 1 for error code.

- src/c++/uds/src/uds/murmurhash3.c
- src/c++/uds/src/uds/numeric.h
- src/c++/uds/userLinux/uds/linux/unaligned.h
- src/c++/vdo/fake/linux/bio.h
unaligned.h file has moved from generated/asm to tools/linux in the kernel include src tree. Add in VDO_USE_NEXT to reflect this change.
> dm vdo: add support for unaligned.h location change

- src/c++/uds/userLinux/build/Makefile
- src/c++/uds/userLinux/tests/albtest.c
- src/c++/vdo/tests/vdotest.c
- src/c++/vdo/user/vdoFormat.c
[VDO-5815] The libuds library that vdoformat was using was built so that it would abort on assertion failures. This should only be happening in uds and vdo unit tests. To fix this, we make sure the NDEBUG flag is always set on libuds. Then inside albtest.c and vdotest.c we set the abort on assert failure flag to true at the start of each test and set it back to its original value at the end.
In addition, we want to improve on the error handling in vdoformat when we get UDS_ASSERTION_FAILURE errors. So we change the error result to VDO_BAD_CONFIGURATION since it is more useful and we add an addition bit of error text to point the users at the actual assertion failure which is written into the logs.
> [VDO-5815] dm vdo user: Fix assertion failures in vdoformat

- doc/vdo.rst
- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/flush.c
- src/c++/vdo/base/message-stats.c
- src/c++/vdo/base/repair.c
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/fake/linux/bio.h
- src/packaging/kpatch/MANIFEST.yaml
The PR is about cleaning up discrepancies between dm-linux and vdo-devel, now that the former has been rebased on top of the 6.11 kernel.
Commit 1 brings back some minor format tweaks I made when pushed commits upstream that I neglected to pull back to vdo-devel.
Commit 2 incorporates a commit that went into 6.10, but not through the dm tree so I managed to overlook it.
Commit 3 strips VDO_USE_NEXT from our upstream code like our other code-inclusion variables.
Commit 4 changes the #ifdefs around the new min_heap interface now that that code has finally landed in 6.11.
> [VDO-5830] Align vdo-devel with rebased dm-linux.

- src/perl/Permabit/BlockDevice/VDO.pm
- src/perl/Permabit/KernelModule.pm
- src/perl/Permabit/ModuleBase.pm
- src/perl/Permabit/UserModule.pm
- src/perl/dmtest/DMTest.pm
- src/perl/dmtest/Makefile
- src/perl/nightly/NightlyBuildType/VDO.pm
- src/perl/vdotest/Makefile
- src/perl/vdotest/VDOTest.pm
This PR contains 3 commit:
. Update useUpstreamKernel flag to useDmVdoModule
. Add useUpstreamModule option to load upstream dm-vdo for testing instead of kvdo. We check if 
useLinuxNextModule is 1, and set the appropriate modName when modprobe is called in KernelModule.
We sill need to load the kvdo module because the user module vdo still requires kvdo to be loaded.
. Add useUpstream test suite
> dm vdo: rename useUpstreamKernel , add useUpstreamModule flag and useUpstream test suite

- src/perl/Permabit/SupportedScenarios.yaml
- src/perl/vdotest/VDOTest/SimpleMigration.pm
X86_RHEL9_head as a scenario is no longer a valid choice since Chlorine. Add X86_FEDORA40_HEAD in SupportedScenarios.yaml so it can be used as a scenario for migration tests.
> dm vdo: Update migration initialScenario to X86_FEDORA40_HEAD

- src/packaging/github/MANIFEST.yaml
- src/packaging/src-dist/MANIFEST.yaml
Define VDO_UPSTREAM and undefine VDO_USE_ALTERNATE and VDO_USE_NEXT in manifests used for userspace releases so that these tokens are properly stripped in dm-vdo/vdo.
We haven't previously used this technique for files published with our user tools, but some recent file motion upstream makes it relevant now.
> Strip alternate tokens from userspace releases

- src/perl/dmtest/Makefile
- src/perl/vdotest/Makefile
This makes all dm-linux CI tests use our regular Fedora machines, which means we always have a single kernel version that the dm-linux repo needs to support. Using RAWHIDE is more forward-looking, but using it would require version-based #ifdefs like we have in vdo-devel, and that's not good in a repository targetted at upstream.
Also removed platform tests from the CI, since we don't care about anything but the newest version for dm-linux.
This PR should make CI tests work on dm-linux again. Currently they are caught between the incompatible nature of 6.11 (F39 and F40) and 6.12 (RAWHIDE, FEDORANEXT).
> dm vdo test: use fedora for dm-linux dmtests

- src/c++/uds/kernelLinux/uds/uds-module.c
- src/c++/uds/src/uds/index-layout.c
- src/c++/uds/src/uds/indexer.h
- src/c++/vdo/base/data-vio.c
- src/c++/vdo/base/data-vio.h
This mirrors two upstream patches from David Alan Gilbert that have been applied to linux-next:
2ca99346cd62 ("dm vdo: Remove unused functions")
29e11586b56a ("dm vdo: Remove unused uds_compute_index_size")
> [VDO-5831] Internalize functions unused in the upstream kernel

- src/perl/Permabit/BlockDevice/VDO.pm
[VDO-5852] [VDO-5853] With latest lvm, 2.03.25, lvm will load upstream vdo module(dm_vdo) if our test module kvdo module is not loaded. Add code to load the desire module before we lvm is called so the proper module is loaded.
> [VDO-5852] [VDO-5853] load kvdo module after reboot

- src/perl/vdotest/VDOTest/VDOFormat.pm
In the tryIllegal function in VDOFormat.pm, we pass in an error string parameter that is used to search through the error output of calls to vdoformat. The calls to vdoformat are done through a function called assertExecuteCommand which calls the perl function confess when an error occurs. Confess attaches a stack trace to the error output which means the search would always succeed because part of the stack trace would contain the error string we're looking for in the tryIllegal parameter part of the stack trace.
The fix for this issue is to be more restrictive in the search criteria so that it only looks at the actual output from vdoformat.
> Fix VDOFormat.pm regexp

- src/perl/vdotest/vdotests.suites
Create03 uses sysfs but the upstream kernel module does not load sysfs so this test will fail. Disable Create03 from upstreamTests suite. Once sysfs test is removed in general, we can restore this test.
> [VDO-5864] dm vdo test: exclude Create03 test

- src/c++/defines
Stop checking zero-length-array in clang that could cause the following error:
repair.c:70:1: error: zero size arrays are an extension [-Werror,-Wzero-length-array] DEFINE_MIN_HEAP(struct numbered_block_mapping, replay_heap); ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ../../../c++/vdo/fake/linux/min_heap.h:49:75: note: expanded from macro 'DEFINE_MIN_HEAP'
#define DEFINE_MIN_HEAP(_type, _name) MIN_HEAP_PREALLOCATED(_type, _name, 0)
This fixes the current build issue with mainline-next.
Also, sort the variable alphabetically.
> dm vdo test: Add -Wno-zero-length-array to CLANG_ONLY_WARNS variable

- src/c++/uds/src/tests/testPrototypes.h
- src/c++/uds/src/uds/time-utils.h
Commit d1fd9729142 upstream add us_to_ktime() to the kernel. This causes a conflict with the version that we created years ago for our tests. So move us_to_ktime) to time-utils.h, and make sure we define it only a) in userspace; or b) when it is not already defined in the kernel.
Also change the parameter on us_to_ktime() and seconds_to_ktime() to be unsigned, to align with the parallel kernel functions.
This fixes the current build issue with mainline-next.
> Use in-kernel us_to_ktime() if available

- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/io-submitter.c
- src/c++/vdo/base/io-submitter.h
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/base/slab-depot.h
- src/c++/vdo/base/types.h
- src/c++/vdo/base/vio.c
- src/c++/vdo/base/vio.h
- src/c++/vdo/tests/BlockMapTreeWrites_t1.c
- src/c++/vdo/tests/SlabJournalRecovery_t1.c
- src/c++/vdo/tests/VIOPool_t1.c
- src/c++/vdo/tests/blockAllocatorUtils.c
Allocates a new pool of metadata VIOs with larger buffers so the reference count data can be read in larger chunks than 4kB.
> [RHEL-12834,VDOSTORY-288,VDO-5613] dm vdo: use larger I/Os when reading slab refcount data

- src/c++/vdo/base/vdo.c
This fix was inspired by the upstream conversation with John Garry. This eliminates a warning for snprintf possibly truncating the MODULE_NAME string (even though in practice it's never that long), but also there's no reason for us to be setting a local value for the MODULE_NAME, and a six-byte prefix string is longer than we want anyway.
> dm vdo: use a short static string for thread name prefix

- src/c++/vdo/base/vdo.c
This is an adjustment to commit c76a00e4b6a0 from PR 226, based on upstream feedback, and will be squashed into that one for upstream.
> dm vdo: remove unnecessary null check

- src/c++/uds/src/tests/RadixSort_t1.c
- src/c++/uds/src/uds/index-layout.c
- src/c++/uds/src/uds/time-utils.h
This MR fixed two build problems:
. update array initialize to prevent the latest gcc 15.0.1 warning.
error: initializer-string for array of ‘unsigned char’ is too long
[-Werror=unterminated-string-initialization]
. update USE_VDO_NEXT comparison marco to include
us_to_ktime() online definition in latest RAWHIDE, 6.13.0 release.
> dm vdo: fix latest rawhide build problem

- src/c++/vdo/base/vdo.c
This is more upstream feedback on the thread name patch, will be squashed upstream into the existing patch.
See PRs 226 and 229.
Simplify the format string, and remove some unnecessary #includes. Actually a good number of the linux #includes seem to not be necessary, but I only removed the ones where I could make a plausible argument to relate them to the module handling.
> dm vdo: simplify format and includes

- src/perl/Permabit/BlockDevice/VDO.pm
- src/perl/vdotest/VDOTest/Create03.pm
Replace regular expressions looking for thread names with new thread name format.
Also adjust Create03 to correctly verify that all thread names include an instance number where they can.
> [VDO-5859] [VDO-5879] dm vdo test: adjust for new error strings

- src/c++/vdo/base/constants.h
- src/c++/vdo/base/encodings.c
These checks support our unit tests, but they can't fail in the kernel module, so remove them from there.
The MINIMUM_VDO_SLAB_JOURNAL_BLOCKS value isn't worth checking even in unit tests.
I noticed some of these while reviewing Bruce's formatting PR.
> dm vdo: remove checks that can not fail

- .github/workflows/ci.yml
Change the approver ci for outside submissions to be anyone in the entire dm-vdo org, instead of the current czar. Switch to using the VDODEVEL secret since that should have the permissions we need to get everyone in dm-vdo.
> ci: allow org members to approve outside submitter PRs

- src/c++/vdo/user/man/vdoformat.8
- src/c++/vdo/user/vdoFormat.c
Prevent users from trying to use small slab sizes which were only intended for unit test scenarios.
I've picked 13 bits (32M) somewhat arbitrarily, it could be as loarge as 15 bits (128M) instead.
I do not expect to merge this to Chlorine (RHEL 9), since it's technically a change to the behavior of vdoformat.
> [VDO-5886] dm vdo user: increase minimum slab size for users

- src/c++/vdo/base/block-map.c
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/packer.h
- src/c++/vdo/base/priority-table.c
- src/c++/vdo/base/recovery-journal.h
- src/c++/vdo/base/slab-depot.c
- src/c++/vdo/base/wait-queue.c
Rings were a list-like abstraction replaced by lists, but there are still a couple of confusing references to them. Fix those.
> Remove a couple of remaining references to rings.

- src/c++/vdo/base/encodings.h
- src/c++/vdo/kernel/Makefile.module.in
Add some kernel module build options taken from W=1 builds.
Fix a warning produced by one of those options.
We don't want to actually use W=1 in our current development builds because that produces many warnings about how we were advised to write our doc strings.
> dm vdo: minor cleanups and build changes based on W=1 module build

- src/perl/Permabit/BlockDevice/VDO/LVMVDO.pm
The function changeVDOSetting in LVMVDO.pm was using the wrong name for the pool. It should have been using getLVMVDOName.
I've also updated a couple comments that were incorrect.
> [VDO-5889] Fix device name used in changeVDOSetting

- src/c++/vdo/base/dedupe.c
A complaint "trying to register non-static key" was generated when using VDO in a kernel with lock debugging enabled. "The code is fine but needs lockdep annotation, or maybe you didn't initialize this object before use?" The latter turns out to be the case.
> [RHEL-59337] dm vdo: add missing spin_lock_init

- src/perl/vdotest/VDOTest/Sysfs.pm
Commit b3872222 changes the VDO device creation sequence such that this test only starts the device once, as opposed to the start-stop-start sequence that used to happen. This changes the instance number assigned to the device, which most tests don’t care about but this one checks.
> [VDO-5888] dm vdo test: update expected instance number for test changes

- src/c++/uds/src/uds/index-session.c
- src/c++/uds/src/uds/indexer.h
- src/c++/uds/userLinux/uds/linux/stddef.h
- src/packaging/src-dist/MANIFEST.yaml
Saves 48 kB (about 12%) per struct hash_zone.
> dm vdo indexer: reorder uds_request to reduce padding

- src/perl/Permabit/BlockDevice/VDO.pm
The addition of auto deactivation within the lvcreate calls create scenarios where vdoformat is not called until the device is activated. This means the timing between creation and wiping of old formatting through vdoformat calls is now changed, causing certain tests to fail.
This commit fixes the issue by calling wipefs on the VDO storage device in the configure() method of VDO.pm. This will wipe the geometry block; allowing calls like lvresize to pass because they do not find any old signature there.
We log the output of the wipefs call because it is very useful to see what is being wiped or not.
> [VDO-5890] Fix issue with auto activation

- src/c++/defines
- src/c++/devices/corruptor/Makefile
- src/c++/devices/corruptor/Makefile.common
- src/c++/devices/corruptor/Makefile.dkms
- src/c++/devices/dory/Makefile
- src/c++/devices/dory/Makefile.common
- src/c++/devices/dory/Makefile.dkms
- src/c++/devices/fua/Makefile
- src/c++/devices/fua/Makefile.common
- src/c++/devices/fua/Makefile.dkms
- src/c++/devices/tracer/Makefile
- src/c++/devices/tracer/Makefile.common
- src/c++/devices/tracer/Makefile.dkms
- src/c++/uds/kernelLinux/defines
- src/c++/uds/kernelLinux/tests/Makefile
- src/c++/vdo/kernel/Makefile.common
- src/c++/vdo/kernel/Makefile.module.in
- src/packaging/dmlinux/kernel/Makefile
- src/packaging/rpm/kernel/Makefile
- src/packaging/src-dist/kernel/Makefile
- src/packaging/src-dist/kernel/vdo/Makefile
- src/packaging/src-dist/user/utils/vdo/Makefile
Based on:
https://www.kernel.org/doc/Documentation/kbuild/makefiles.txt
EXTRA_FLAGS has been deprecated. We should be using ccflags-y. Replaced EXTRA_CFLAGS with ccflags-y in all our files.
> Replace EXTRA_CFLAGS with ccflags-y

- src/c++/uds/src/uds/time-utils.h
RHEL10 does not have a us_to_ktime definition, we need to exclude RHEL10 in VDO_USE_NEXT definition.
> [TECH-189] Change RHEL_RELEASE_VERSION comparison to exclude RHEL10

- src/perl/Permabit/AlbireoTestUtils.pm
Merge (well, cherry-pick) perl test changes from PR 252 on to the 8.3 (RHEL 10) release branch. This allows VDO perl tests to run on that branch.
> Merge PR 252 to 8.3

- doc/vdo.rst
This is a follow-up to PR 269, the lz4 compression type feature. Bruce pointed out I forgot to document the changes to the
status output. When pushing upstream, I intend to squash this cahnge with the previous doc commit ([cb80514](https://github.com/dm-vdo/vdo-devel/commit/cb8051445b3f1fcfadf1e9d3f3329d280d80b5b3)).
> [VDO-5892] Document compression changes to status

- doc/vdo.rst
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/tests/asyncLayer.c
- src/perl/Permabit/BlockDevice/VDO.pm
- src/perl/vdotest/VDOTest/CompressDedupeDefaults.pm
- src/perl/vdotest/VDOTest/Dmsetup.pm
- src/perl/vdotest/VDOTest/MemoryFail01.pm
- src/perl/vdotest/VDOTest/MultipleDevices.pm
- src/perl/vdotest/VDOTest/Sysfs.pm
This idea came up while reviewing PR #269. It renames the 'online' and 'offline' index states, and updates the docs to include the 'suspended' state.
While updating tests, it also fixes a problem with test expectations for compression status output that doesn't seem to have a ticket yet.
> [VDO-5896] Rename misleading index states and update tests

- src/perl/Permabit/BlkTrace.pm
- src/perl/Permabit/BlockDevice.pm
Another random grab-bag. See [common#4](https://github.com/dm-vdo/common/pull/4) for the removal of SupportUtils, which depends on the BlkTrace change.
> tiny perl polishings for easier no-permabit-copr fedora use

- doc/vdo.rst
- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/tests/asyncLayer.c
- src/perl/Permabit/BlockDevice/VDO.pm
- src/perl/vdotest/VDOTest/CompressDedupeDefaults.pm
- src/perl/vdotest/VDOTest/Dmsetup.pm
- src/perl/vdotest/VDOTest/MemoryFail01.pm
- src/perl/vdotest/VDOTest/MultipleDevices.pm
- src/perl/vdotest/VDOTest/Sysfs.pm
Comments from Zdenek make it clear that VDO can only change the status line output when we are passing new parameters. The status line output for device where whe only use existing parameters must be the same as it always was. So in the case of the compressionType parameter, we can provide more informative status output when the --compressionType parameter is set, but not when it is not set.
Commits 1-3 revert status line changes that break backwards compatibility. (and related documentation).
Commit 4-6 implement the new behavior and documentation.
Commit 3 fixes VDO-5897 by allowing dmeventd to parse VDO's status line again.
Commit 1 reverts the fix for VDO-5896, but commit 3 reverts the change that caused VDO-5896, so that issue should remain fixed.
Commit 3 and 4 could be squashed …
> [VDO-5892][VDO-5896][VDO-5897] Restore old status line output when compression type is not set

- src/c++/vdo/base/dedupe.c
- src/c++/vdo/fake/linux/timer.h
- src/c++/vdo/tests/testTimer.c
The linux-next branch recently took a tree-wide update that renamed del_timer_sync() to timer_delete_sync()
(8fa7292fee5c "treewide: Switch/rename to timer_delete[_sync]()"). vdo-devel needs to incorporate this change (already done in dm-vdo upstream) in order to build on linux-next.
This change will not go upstream because it ingests changes that have already been made upstream, not through the device-mapper tree.
> Fix vdo-on-latest-kernel-snapshot build

- src/c++/uds/src/uds/time-utils.h
Switch us_to_ktime #ifdefs from VDO_USE_NEXT to VDO_USE_ALTERNATE now that Fedora kernels have incorporated the function, new in 6.14 kernels.
This is necessary to make Dist perl tests work again, including for CI.
> Update us_to_ktime ifdef handling

- src/c++/uds/src/tests/Volume_n4.c
- src/c++/uds/src/uds/volume.c
The function get_volume_page_protected() may place a request on a queue for another thread to process asynchronously. When this happens, the volume should not read the request from the original thread. This can not currently cause problems in UDS, because the read thread will requeue the request on the zone thread after the page is in the cache, so the request cannot be completed or altered before get_volume_page_protected() and its callers complete.
However, in Volume_n4 we replace the normal retryRead function with a hook that verifies the page data and then frees the request. This means that the post-enqueue parts of the relevant functions can read freed memory (causing a segmentation fault, as in VDO-5642) or they may see a new request allocated in the same location with a different …
> [VDO-5642][VDO-5644] Fix Volume_n4 test issues

- src/c++/vdo/tests/BlockMapRecovery_t1.c
Don't free the repair_completion until the vdo_repair operation has completed.
> [VDO-5649] Fix race in BlockMapRecovery_t1

- src/c++/devices/common.c
- src/c++/devices/common.h
linux-next just got a change to the prepare_ioctl function signature in dm core. dm-vdo itself does not use this hook but our tests devices do, so adjust those hook signatures to match upstream. This is late enough that it probably won't get released wih 6.15, so we may need to adjust the version numbers for the switchover later.
his PR should fix the linux-vdo-against-latest-kernel-snapshot build.
> Adapt to upstream prepare_ioctl changes in linux-next

- src/perl/Permabit/ScriptFramework.pm
ScriptFramework.pm causes an error during "make jenkins" in F41 with the 
following warning:
Name "main::log" used only once: possible typo at ./ScriptFramework.pm line 169.
Add ScriptFramework.pm to the NO_CHECK list.
> [Tech-203] Disable 'used only once' warning

- src/perl/Permabit/Grub.pm
Starting with RHEL9, we need to use command line grubby to adjust kernel memory limit. Since we have no RHEL8 in our lab, replace the RHEL9 test, isPlow(), with isRedHat() to adjust kernel memory limit.
> [VDO-5903] dm vdo test: Fix KernelUtils LowMemGenData01 test

- src/perl/Permabit/VolumeGroup.pm
For some reason, we forgot to add $dataType to the lvcreate string in createThinPool, which is what is needed to create proper vdo thin pools.
> dm vdo test: fix createThinPool in VolumeGroup.pm

- src/c++/vdo/base/dedupe.c
Ingest changes from commit 41cb08555c41 ("treewide, timers: Rename from_timer() to timer_container_of()") on linux-next.
This will get us back in sync with with the current statue on linux-next and thus fix the linux-vdo-against-current-vdo-snapshot job.
> dm vdo dedupe: rename from_timer per linux-next

- src/perl/Permabit/Grub.pm
With Fedora 42, the grub cmdline line in /etc/default/grub is GRUB_CMDLINE_LINUX_DEFAULT. We test if a host is Fedora 42 and set up the proper GRUB2_EDIT string.
> [VDO-5912] dm vdo test: Fix KernelUtils LowMemGenData01 with Fedora 42

- src/c++/vdo/base/dedupe.c
- src/c++/vdo/base/dedupe.h
- src/c++/vdo/base/dm-vdo-target.c
- src/perl/Permabit/BlockDevice/VDO.pm
- src/perl/vdotest/VDOTest/Sysfs.pm
[VDO-5864] Remove all usage of dedupe sysfs fields. This is an internal change only, since the sysfs fields have already been removed from the upstream vdo code.
> dm vdo tests: Remove vdo/dedupe sysfs fields

- src/c++/vdo/base/dedupe.c
- src/c++/vdo/fake/linux/timer.h
Fix the macro to set VDO_USE_NEXT in RAWHIDE and FEDROANEXT distro
for from_timer change in pull request 304:
https://github.com/dm-vdo/vdo-devel/pull/304
The change in pull request should also apply to src/c++/vdo/fake/linux/timer.h.
> [VDO-5919] dm vdo test: Fix build problem with RAWHIDE and FEDORANEXT distro

- src/c++/devices/common.c
- src/c++/devices/common.h
Latest Fedora release version has been updated from 14 to 15, but the commonPrepareIoctl definition is not in the latest release yet. We need to update the comparison from 15 to 16 when defining VDO_USE_NEXT.
> dm vdo test: update KERNEL_VERSION comparison from 15 to 16

- src/c++/vdo/base/dm-vdo-target.c
- src/c++/vdo/base/histogram.c
- src/c++/vdo/base/histogram.h
- src/c++/vdo/base/vdo-histograms.c
- src/c++/vdo/base/vdo-histograms.h
- src/perl/Permabit/BlockDevice/VDO.pm
Convert histogram sysfs fields into a dmsetup message string
This commit:
- Adds 'dmsetup message histograms' to output all histogram info into a JSON string
- Adds 'dmsetup message histogram limit' to set histogram limits
- Removes all sysfs references from vdo-histograms.[ch] and histogram.[ch]
- Adds name field to the histogram structure. The sysfs supported a name automatically before
- Adds histogram_is_named() function to compare a histogram's name against a passed in parameter to be used for limit setting
- Adds write_histogram() function to print a histogram's info (as a JSON string) into a buffer
- Adds histogram_write_item() function to print a value into a buffer and then updates the buffer pointer and how much space the buffer has left to print to. This will be used in all …
> [VDO-5864] Replace vdo/histogram sysfs fields with dmsetup message

- src/c++/vdo/base/histogram.c
- src/c++/vdo/base/histogram.h
- src/c++/vdo/base/vdo-histograms.c
- src/c++/vdo/base/vdo-histograms.h
Simplify histogram code in vdo-histograms.c by using an array instead of a hardcoded list of histograms. However, we will maintain the hardcoded list as well during creation so callers of enter_histogram_sample() in vdo code don't need to be updated.
> [VDO-5864] Refactor histogram code

- src/c++/devices/common.c
- src/c++/devices/common.h
In the latest RHEL10, commonPrepareIoct definition has been updated to
the upstream prepare_ioctl mentioned in PR294:
#294
This required us to adopt the change for RHEL10. VDO_USE_NEXT tag no longer
represents the change. Updated our code using VDO_USE_ALTERNATE tag instead.
> Updated commonPrepareIoctl definition in RHEL10

- src/perl/nightly/NightlyBuildType/VDO.pm
RHEL10 uses the VDO test suite for testing.  Since VDO test suites include MAINLINENEXT and RAWHIDE which is not applicable to RHEL10, We have to separate MAINLINENEXT and RAWHIDE suites so they will not be called during RHEL10 tests.
> [VDO-5867] Separate MAINLINENEXT and RAWHIDE test into UPSTREAM_SUITE.

- src/c++/vdo/base/histogram.c
In the make_histogram function, added a call to vdo_free(h) when vdo_allocate fails, ensuring proper memory management and preventing potential memory leaks.
> [VDO-5925] Fix memory leak in histogram creation

- src/c++/uds/src/uds/time-utils.h
us_to_ktime is defined in the latest RHEL10, updating the VDO_USE_ALTERNATE macro to exclude RHEL10.
> Update VDO_USE_ALTERNATE to disable us_to_ktime definition in RHEL10

- src/c++/vdo/base/dedupe.c
- src/c++/vdo/fake/linux/timer.h
Switch VDO_USE_NEXT code block to using VDO_USE_ALTERNATE macro and update the comparsion
of RHEL to cover RHEL10 regardless the minor version.
> dm vdo test: switch VDO_USE_NEXT code block to using VDO_USE_ALTERNATE macro

- src/c++/uds/src/uds/volume-index.c
Someone upstream noticed that we check for, but then ignore, metadata size errors (most likely indicating metadata corruption) when loading the volume-index. So this PR ingests the fix, from upstream commit 9ddf6d3fcbe0 ("dm vdo: return error on corrupted metadata in start_restoring_volume functions").
This problem has existed since change 157986 (and reflected in our initial upstream push). I apparently messed this up while doing some refactoring in the UDS code.
> Ingest upstream fix to return errors on metadata corruption.

- src/packaging/kpatch/Makefile
- src/packaging/kpatch/commit_to_overlay.sh
First in a series of cleaning up and committing improvements to the overlay script that I've been using in my workspace for months, but which I never actually committed.
This one reduces the overlay script's reliance on Makefile targets, and also makes several minor improvements to the format of the generated upstream patches.
ETA: This is a newer version of work that was originally PR #37, so check there for some discussion and comments. But I managed to screw that PR up somehow, so I've made this new one.
> Reduce Makefile dependecies and other overlay script improvements
